services:
  - type: web
    name: face-recognition-streamlit
    env: python
    region: oregon

    buildCommand: |
      apt-get update && apt-get install -y cmake
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
